name: Docker Image CI

on:
  push:
    branches:
      - main
jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      
      
      - name: Configure AWS 
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::592311462240:role/advanced-artefacts-gh-advancedcsg
          aws-region: eu-west-2
     
      ##- name: Set Docker env variables
       ## run: |
        ## echo "docker_image_name=local-assignment-3" >> $GITHUB_ENV
         ## echo "docker_repository=/local-assignment-3" >> $GITHUB_ENV
         ## echo "docker_registry=069705096352.dkr.ecr.eu-west-2.amazonaws.com" >> $GITHUB_ENV
        
      - name: Building the docker
        run: docker build -t html-image:v1 .

      - name: Advanced Artefacts CLI - Setup
        uses: advancedcsg/actions-setup-advanced-artefacts-cli@v1.1.0
    
      - name: Tagging build docker with version tag and latest tag
        run: docker tag html-image:v1 $CONTAINER_IMAGES_REGISTRY/innovation/dev/hello-world:devopstraining
      - name: Publishing to Artifactory with version tag and latest tag
        run: docker push $CONTAINER_IMAGES_REGISTRY/innovation/dev/hello-world:devopstraining